### ISSUE TITLE
Migrate to Yarn

### ISSUE THREAD

**Issue by gabeweaver** [spartansystems/booster-kit-react#23]
So we can have better package and dependency management.

[Yarn Install Docs](https://yarnpkg.com/en/docs/install)

**Comment by bbrock25** [comment]
love it!

**Comment by gabeweaver** [comment]
Here is a commit from refactoring foresight to use yarn - https://github.com/spartansystems/foresight-client/commit/88f5c5150d911cdeb78a5181c3b271302cedf2bf

Sorry about the flow def noise...

**Comment by TheAznShumai** [comment]
This [PR](https://github.com/spartansystems/booster-kit-react/pull/28) migrates npm to yarn.
