### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by TheAznShumai** [spartansystems/booster-kit-react#29]
Dependencies need update.

**Comment by gabeweaver** [comment]
@TheAznShumai what's the status on this? I'm going to do some work to get the booster ready for the new company site...I just didn't want to duplicate efforts with anything you are working on. 

For now, i'll probably start with webpack, but by tomorrow morning, i'll need to move on the rest of the updates (depending on what you're targeting).

**Comment by gabeweaver** [comment]
This is mostly addressed in https://github.com/spartansystems/booster-kit-react/pull/31

**Comment by TheAznShumai** [comment]
i just barely started but i'll close this out
